data:extend({
	{
		type = "string-setting",
		name = "gore-preset",
		setting_type = "startup",
		allowed_values = {"blood-red", "rainbow", "purple", "pink", "green", "puke", "custom/automatic", "custom"},
		default_value = "blood-red",
		order = "a",
		per_user = false,
	},
	{
		type = "color-setting",
		name = "gore-decal_color",
		setting_type = "startup",
		default_value = {3, 172, 115, 153, },
		order = "a0",
		per_user = false,
	},
	{
		type = "color-setting",
		name = "gore-fx_color",
		setting_type = "startup",
		default_value = {0, 128, 105, 153},
		order = "a1",
		per_user = false,
	},
	{
		type = "color-setting",
		name = "gore-particle_color",
		setting_type = "startup",
		default_value = {0,216,185,217},
		order = "a2",
		per_user = false,
	},
	{
		type = "color-setting",
		name = "gore-corpse_blood_color",
		setting_type = "startup",
		default_value = {0,255,211,255},
		order = "a3",
		per_user = false,
	},
	{
		type = "color-setting",
		name = "gore-guts_color",
		setting_type = "startup",
		default_value = {0,105,82,149},
		order = "a4",
		per_user = false,
	},
	{
		type = "double-setting",
		name = "gore-puddle-d",
		setting_type = "startup",
		default_value = 0.9,
		maximum_value = 2,
		minimum_value = 0,
		order = "dh",
		per_user = false,
	},
		{
		type = "double-setting",
		name = "gore-scale",
		setting_type = "startup",
		default_value = 1.05,
		maximum_value = 5,
		minimum_value = 0.01,
		order = "f",
		per_user = false,
	},
		{
		type = "double-setting",
		name = "gore-splatterscale",
		setting_type = "startup",
		default_value = 1.3,
		maximum_value = 5,
		minimum_value = 0.01,
		order = "g",
		per_user = false,
	},
	{
		type = "double-setting",
		name = "gore-particlescale",
		setting_type = "startup",
		default_value = 1,
		maximum_value = 5,
		minimum_value = 0.01,
		order = "h",
		per_user = false,
	},
	{
		type = "int-setting",
		name = "gore-splatterduration",
		setting_type = "startup",
		default_value = 100,
		maximum_value = 9999999,
		minimum_value = 0,
		order = "i",
		per_user = false,
	},
	{
		type = "int-setting",
		name = "gore-particleduration",
		setting_type = "startup",
		default_value = 20,
		maximum_value = 9999999,
		minimum_value = 0,
		order = "j",
		per_user = false,
	},
	{
		type = "int-setting",
		name = "gore-puddleduration",
		setting_type = "startup",
		default_value = 110,
		maximum_value = 9999999,
		minimum_value = 0,
		order = "k",
		per_user = false,
	},
	{
		type = "int-setting",
		name = "gore-bodyduration",
		setting_type = "startup",
		default_value = 120,
		maximum_value = 9999999,
		minimum_value = 0,
		order = "l",
		per_user = false,
	},
	{
		type = "bool-setting",
		name = "gore-change_guts",
		setting_type = "startup",
		default_value = true,
		order = "l1",
		per_user = false,
	},
	{
		type = "double-setting",
		name = "gore-guts_mult",
		setting_type = "startup",
		default_value = 0.5,
		maximum_value = 3,
		minimum_value = 0,
		order = "l2",
		per_user = false,
	},
	{
		type = "bool-setting",
		name = "gore-hide_puddle",
		setting_type = "startup",
		default_value = false,
		order = "n",
		per_user = false,
	},
	{
		type = "bool-setting",
		name = "gore-custom_splashes",
		setting_type = "startup",
		default_value = true,
		order = "ownly",
		per_user = false,
	},
	{
		type = "bool-setting",
		name = "gore-custom_decals",
		setting_type = "startup",
		default_value = true,
		order = "ownlyme",
		per_user = false,
	},
	{
		type = "bool-setting",
		name = "gore-damage-bleeding",
		localised_name = "Damage bleeding",
		localised_description = "This adds additional blood effects when a unit is damaged\nThe damage scales with the damage taken and the amount a unit can maximally bleed is limited by their max health",
		setting_type = "startup",
		default_value = true,
		order = "ownlymeee",
		per_user = false,
	}
	})
if mods["ArmouredBiters"] then

	data:extend({
	
	{
		type = "string-setting",
		name = "gore-armoured_bleed",
		setting_type = "startup",
		allowed_values = {"all", "only decals", "none"},
		default_value = "none",
		order = "zzzzzzz",
		per_user = false,
	},
	})
end