local explosion_animations = require("__base__/prototypes/entity/explosion-animations")

data:extend({
	{
		type = "explosion",
		name = "visual-tracer-explosion-hit-normal",
		flags = {"not-on-map"},
		subgroup = "explosions",
		animations = explosion_animations.dust_explosion(),
		hidden = true,
		rotate = true,
		light = {intensity = 0.5, size = 4, color = {r = 1, g = 0.8, b = 0.4} },
		light_intensity_factor_initial = 1,
		light_intensity_factor_final = 0,
		light_intensity_peak_start_progress = 0,
		light_intensity_peak_end_progress = 0,
		light_size_factor_initial = 1,
		light_size_factor_final = 1,
		
	},
	{
		type = "explosion",
		name = "visual-tracer-explosion-hit-piercing",
		flags = {"not-on-map"},
		subgroup = "explosions",
		animations = explosion_animations.dust_explosion(),
		hidden = true,
		rotate = true,
        light = {intensity = 0.6, size = 4, color = {r = 1, g = 0.6, b = 0.3} },
		light_intensity_factor_initial = 1,
		light_intensity_factor_final = 0,
		light_intensity_peak_start_progress = 0,
		light_intensity_peak_end_progress = 0,
		light_size_factor_initial = 1,
		light_size_factor_final = 1,
	},
	{
		type = "explosion",
		name = "visual-tracer-explosion-hit-uranium",
		flags = {"not-on-map"},
		subgroup = "explosions",
		animations = explosion_animations.dust_explosion(),
		hidden = true,
		rotate = true,
        light = {intensity = 0.6, size = 4, color = {r = 0.7, g = 1, b = 0.5} },
		light_intensity_factor_initial = 1,
		light_intensity_factor_final = 0,
		light_intensity_peak_start_progress = 0,
		light_intensity_peak_end_progress = 0,
		light_size_factor_initial = 1,
		light_size_factor_final = 1,
	},
})
